Introduce better README
v3xlabs/permissio pull request #4
Opened 2022-07-06 23:49 UTC by lucemans

2022-07-06 23:54 UTC, svemat01 requested changes

2022-07-06 23:54 UTC, svemat01 commented on README.md
> +At its core you will be able to create an `enum` for your permissions, so long as the key of which is an integer.
```suggestion
At its core, you will be able to create an `enum` for your permissions, so long as the value of which is an integer.
```

2022-07-06 23:54 UTC, svemat01 commented on README.md
> +Gathering wether permissiondata contains a certain permission is as easy as follows:
```suggestion
Gathering whether permissiondata contains a certain permission is as easy as follows:
```

2022-07-06 23:54 UTC, svemat01 commented on README.md
> +Using Permissio simplifies permission manipulation and storage through intelligent use of bitfields.
```suggestion
Using Permissio simplifies permission manipulation and storage through the intelligent use of bitfields.
```

2022-07-06 23:58 UTC, svemat01 requested changes
Maybe explain how enums only exists in typescript and the alternative solution on plain javascript

2022-07-07 00:13 UTC, svemat01 approved these changes
Javascript clarification was agreed between myself and @lucemans to be extended on / created in a new PR.

2022-07-07 08:47 UTC, Antony1060 approved these changes
LGTM

2022-07-07 09:02 UTC, merged