Update testing
v3xlabs/permissio pull request #7
Opened 2022-07-07 14:10 UTC by Antony1060

2022-07-07 14:11 UTC, Antony1060 commented
Someone please change the README to have docs for the non tree-shakeable functions and push to this branch.

2022-07-09 13:54 UTC, lucemans requested changes
Not sure about the `new` keyword, what do you think about `createPermissions` `instantiatePermissions` `makePermissions`.

I think I like create better, but not sure

2022-07-09 13:54 UTC, lucemans commented on src/index.ts
> +export const newPermissions = (root: bigint = EMPTY_PERMISSIONS) => {
Not sure about the use of the reserved keyword `new`..
Default is a smart move!

2022-07-09 14:44 UTC, Antony1060 commented on src/index.ts
> +export const newPermissions = (root: bigint = EMPTY_PERMISSIONS) => {
I like `make` and `create`. So let's go with `create`.

2022-07-10 21:59 UTC, svemat01 approved these changes
LGTM

2022-07-12 12:30 UTC, lucemans approved these changes
LGTM

2022-07-12 12:30 UTC, merged